name: "Setup project"
runs:
  using: "composite"
  steps:
    - name: Read version from package.json
      shell: bash
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VITE_SZ_VERSION=${VERSION}" >> $GITHUB_ENV
        echo "VITE_SZ_VERSION_INFO=${VERSION}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Linter
      shell: bash
      run: pnpm lint
